spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  config:
    activate:
      on-profile: local
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.walmart.aex.strategy.service: info
    org.hibernate.SQL: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} AEX-STRATEGY-SERVICE [%thread] %-5level %logger{36} - %msg%n"
memcached.cache:
  provider: appengine
  expiration: 24h
runtime:
  context:
    appVersion: 1.0.0-SNAPSHOT
    environment: DEV
    system:
      property:
        override:
          enabled: true
    environmentType: dev
    appName: aex-strategy-service

scm:
  server:
    access:
      enabled: true
  snapshot:
    enabled: true
---
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  config:
    activate:
      on-profile: dev
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.walmart.aex.strategy.service: info
    org.hibernate.SQL: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} AEX-STRATEGY-SERVICE  [%thread] %-5level %logger{36} - %msg%n"
memcached.cache:
  provider: appengine
  expiration: 24h

runtime:
  context:
    appVersion: 1.0.0-SNAPSHOT
    environment: DEV
    system:
      property:
        override:
          enabled: true
    environmentType: dev
    appName: aex-strategy-service

scm:
  server:
    access:
      enabled: true
  snapshot:
    enabled: true
---
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  config:
    activate:
      on-profile: stg
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.walmart.aex.strategy.service: info
    org.hibernate.SQL: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} AEX-STRATEGY-SERVICE [%thread] %-5level %logger{36} - %msg%n"
memcached.cache:
  provider: appengine
  expiration: 24h

runtime:
  context:
    appVersion: 1.0.0-SNAPSHOT
    environment: STG
    system:
      property:
        override:
          enabled: true
    environmentType: stg
    appName: aex-strategy-service

scm:
  server:
    access:
      enabled: true
  snapshot:
    enabled: true
---
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  config:
    activate:
      on-profile: prod
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.walmart.aex.strategy.service: info
    org.hibernate.SQL: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} AEX-STRATEGY-SERVICE [%thread] %-5level %logger{36} - %msg%n"
memcached.cache:
  provider: appengine
  expiration: 24h

runtime:
  context:
    appVersion: 1.0.0-SNAPSHOT
    environment: PROD
    system:
      property:
        override:
          enabled: true
    environmentType: prod
    appName: aex-strategy-service

scm:
  server:
    access:
      enabled: true
  snapshot:
    enabled: true
---
management:
  health:
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - loggers
          - metrics
          - prometheus
    health:
      show-details: always
  endpoint:
    loggers:
      enabled: true
