apiVersion: 2.0
kind: ServiceConfig
metadata:
  serviceConfigVersion: 1.3-PROD
  serviceId: AEX_STRATEGY_SERVICE
  deliveryEnvironment: PROD
  authzPolicies:
    adminUI:
      adminGroups:
        - "apparel-precision-kitt"
    git:
      org: "ApparelPrecision"
      repo: "aex-strategy-service"
      branch: "main"
  externallyReferencedServiceConfig:
    - serviceId: AEX_SECURITY_COMMON
      serviceConfigVersion: 1.4
  notifications:
    slack:
      channel: apparel-precision-ops
configDefinitions:
  databaseConfig:
    description: ""
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "sqlServer.url":
        description: "AEX Strategy Service SQL Server DB URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "jdbc:sqlserver://aex-strategy-prd-prod-62bede24-failover-group.database.windows.net:1433;database=us_wm_aex_strategy;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryPassword"
      "sqlServer.driverClassName":
        description: "SQL Server Driver Class Name"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
      "sqlServer.connection.pool.initial.size":
        description: "Connection Pool Initial Size"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 3
      "sqlServer.connection.max.active":
        description: "Max Active Connections"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 5
      "sqlServer.connection.timeout.ms":
        description: "Connection Timeout in milliseconds"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 30000
      "sqlServer.connection.max.life.time.ms":
        description: "Max connection lifetime in milliseconds"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 180000
      "sqlServer.connection.idle.timeout.ms":
        description: "Idle connection timeout in milliseconds"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 30000
  midasConfig:
    description: "Midas Data API Service to Service Authentication"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "midas.baseURL":
        description: "Midas api base url"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "http://midas-data-api.prod.midas-api.catdev.prod.us.walmart.net/api/workflow/v1/execute"
      "midas.apRankingMetricsQuery":
        description: "To fetch AP Ranking Metrics from ClickHouse database workflow"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "{\"query\": { \"select\": [ { \"field\": \"*\" } ], \"from\": \"get_apRanking_metrics\", \"params\": { \"l1Id\": \"%s\", \"l2Id\": \"%s\", \"finelineNbr\": \"%s\", \"season\": \"%s\", \"fiscalYear\": \"%s\"}}}"
      "midas.header.consumer":
        description: "Midas api header consumer Id"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "13705f9d-3eb8-46b5-b2c1-63a1b569af4c"
      "midas.header.signatureKeyVersion":
        description: "Midas api header signature Key Version"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "1"
      "midas.header.signatureAuthFlag":
        description: "Midas api header signature Auth   Flag"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "true"
      "midas.header.signatureTS":
        description: "Midas api header signature TS"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "1639068838648"
      "midas.header.tenant":
        description: "Midas api header tenant"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "aex"
  httpConfig:
    description: "HTTP Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "http.connectTimeout":
        description: "Connection Timeout for HTTP Calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 180000
      "http.connectionRequestTimeout":
        description: "Connection Request Timeout for HTTP Calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 180000
      "http.readTimeout":
        description: "Read Timeout for HTTP calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 180000
  appConfig:
    description: "app Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "weatherClusterStrategyId":
        description: "weatherClusterStrategyId"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 1
      "fixtureStrategyId":
        description: "fixtureStrategyId"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 10
      "getCluster1OffshoreList":
        description: "exclude offshore list for cluster1"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "PR"
      "getCluster2OffshoreList":
        description: "exclude offshore list for cluster1"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "HI"
      "getCluster7OffshoreList":
        description: "exclude offshore list for cluster7"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "AK"
      "ahsUrl":
        description: "AHS URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "https://attributehelper.apparel.walmart.net/retrieveValuesByHierarchy"
      "ahsConsumerId":
        description: "AHS ConsumerID"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "dc9f42fa-851d-49cc-b3f6-356f6c64b24b"
      "ahsEnv":
        description: "AHS Env"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "prod"
      "ahsAttributeTypes":
        description: "List of Attributes pulled from AHS"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "colorFamily"
          - "fabricConstruction"
          - "fabricType"
          - "fashionPyramid"
          - "lifestyle"
          - "newness"
          - "patternType"
          - "priceTier"
          - "silhouette"
          - "clothingSizeGroup"
          - "brandCategory"
          - "sizeRanges"
      "csaUrl":
        description: "CSA URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "https://mds-csa-report.walmart.com/v1/csa-service/ap-data/reserved-programs"
      "csaEnv":
        description: "CSA Env"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "prod"
      "size.pack.release.flag":
        description: "enable/disable size & pack code for UAT & PROD release"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "true"
      "size.pack.spread.feature.flag":
        description: "enable/disable size & pack spread logic functionality"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "true"
      "ap.s1.release.flag":
        description: "enable/disable always setting inStore & markDown Dates code for UAT & PROD release"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "true"
      "strategy.aptbls.release.flag":
        description: "enable/disable Assort Product code for UAT & PROD release"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "true"
      "vd.analytics.clusterGroupDesc":
        description: "volumeDeviationAnalyticsClusterGroupDesc"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "Volume Deviation"
      "ap.s4.release.flag":
        description: "enable/disable always setting MIDAS Integration"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "false"
      "csaProgramsPlanId":
        description: "Plan Ids that needs all the programs from CSA"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "62"
          - "68"
          - "69"
          - "72"
          - "85"
          - "88"
          - "89"
          - "96"
          - "99"
          - "112"
          - "114"
          - "115"
          - "123"
          - "128"
          - "129"
          - "133"
          - "134"
          - "144"
          - "149"
          - "151"
          - "155"
          - "157"
          - "160"
          - "161"
          - "162"
          - "163"
          - "167"
          - "171"
          - "172"
          - "174"
          - "176"
          - "183"
          - "189"
  kafkaConfig:
    description: "Kafka Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "aex.strategy.service.kafka.server":
        description: "Kafka Broker list for AEX Strategy Service topic"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "kafka-420262885-1-1196111317.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-2-1196111320.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-3-1196111323.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-4-1196111326.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-5-1196111329.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-6-1196111332.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-7-1196111335.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-8-1196111338.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-9-1196111341.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-10-1196111344.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-11-1196111347.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-12-1196111350.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-13-1196111353.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-14-1196111356.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093,kafka-420262885-15-1196111359.scus.kafka-v2-shared1-ssl-prod.ms-df-messaging.prod-az-southcentralus-2.prod.us.walmart.net:9093"
      "aex.strategy.service.kafka.topic":
        description: "Kafka Topic for AEX Strategy service"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "aex_strategy_service_prod"
  rfaGraphQlConfig:
    description: "GraphQL Config"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "rfa.space.assortproduct.url":
        description: "Get RFA output from Assort Product Service"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "https://assortproduct.aex.prod.walmart.net/graphql"
      "rfa.space.assortproduct.fineline.query":
        description: "Query to retrieve RFA Fineline output"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "query ($request:RFARequest!)\n {\n getRFAFinelineSpaceAllocation(request:$request)\n {\n rfaFinelineData{\n plan_id_partition\n rpt_lvl_0_nbr\n rpt_lvl_1_nbr\n rpt_lvl_2_nbr\n rpt_lvl_3_nbr\n rpt_lvl_4_nbr\n fineline_nbr\n customer_choice\n }}}"
      "rfa.space.assortproduct.stylecc.query":
        description: "Query to retrieve RFA Style and CC output"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "query ($request:RFARequest!)\n {\n getRFAStyleCcSpaceAllocation(request:$request)\n {\n rfaStylesCcData{\n plan_id_partition\n rpt_lvl_0_nbr\n rpt_lvl_1_nbr\n rpt_lvl_2_nbr\n rpt_lvl_3_nbr\n rpt_lvl_4_nbr\n fineline_nbr\n style_nbr\n customer_choice\n }}}"
      "rfa.space.assortproduct.consumer.id":
        description: "Consumer ID to call Assort Product"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "79be7e4b-28a6-45a9-bba5-30a6449d7b1d"
      "rfa.space.assortproduct.consumer.name":
        description: "Consumer svc name"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "AEX_ASSORTPRODUCT_SERVICE"
      "rfa.space.assortproduct.consumer.env":
        description: "Consumer Environment"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "prod"

  featureConfig:
    description: "Feature Flag Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "is.save.default.volume.deviation.enabled":
        description: "Default value to save default volume deviation"
        type: "BOOLEAN"
        kind: "SINGLE"
        defaultValue: true
      "sp.save.total.size.percent.enabled":
        description: "feature flag to enable saving sum of all eligible sizes"
        type: "BOOLEAN"
        kind: "SINGLE"
        defaultValue: true
  executorConfig:
    description: "Executor Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "fixedThreadPool.count":
        description: "Thread pool count"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 5
